### ISSUE TITLE
Colocar página no GitHub docs (github.io)

### ISSUE THREAD

**Issue by fabriciofx** [devanessacarvalho/ifpe-paulista-ads#5]
Veja os procedimentos para hospedar a página no github docs e assim podemos navegar no site.

**Comment by devanessacarvalho** [comment]
Acabei não lembrando de mencionar a issue no commit kk.
Mas consegui hospedar aqui e inclui o readme com link de acesso a cada página
https://github.com/devanessacarvalho/ifpe-paulista-ads/commit/79357a7163a9345dbad87066eb03cce449f626a3
