### ISSUE TITLE
O for do label promotions deveria ser igual ao id do checkbox

### ISSUE THREAD

**Issue by fabriciofx** [devanessacarvalho/ifpe-paulista-ads#9]
O atributo `for` do `label` promotions deveria ser igual ao `id` do checkbox.

**Comment by devanessacarvalho** [comment]
ksksk fui copiar  do de notificações e esqueci de troacar a label 😅

**Comment by fabriciofx** [comment]
> ksksk fui copiar do de notificações e esqueci de trocar a label 😅

@devanessacarvalho acontece!

**Comment by fabriciofx** [comment]
@devanessacarvalho done!
